#!/usr/bin/env bash
# This script pings an IP address passed as an argument
# It accepts a string as an argument
# It displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# It pings the IP 5 times

# Check if an argument is provided
if [ $# -eq 0 ]; then
  # No argument, display usage message
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Assign the argument to a variable
IP=$1

# Ping the IP 5 times
ping -c 5 $IP